version: '3.8'
services:
  eliza:
    build: .
    ports:
      - "3000:3000"
      - "50000-50100:50000-50100/udp"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://eliza:eliza@db:5432/eliza
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: eliza
      POSTGRES_PASSWORD: eliza
      POSTGRES_DB: eliza
    ports:
      - "5432:5432" 