version: '3.8'

services:
  # ElizaOS Production Service
  eliza:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elizaos-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "50000-50100:50000-50100/udp"
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      # Core Configuration
      NODE_ENV: ${NODE_ENV:-development}
      API_PORT: ${API_PORT:-3000}
      PORT: "3000"
      LOG_LEVEL: ${LOG_LEVEL:-debug}
      HOST: "0.0.0.0"
      
      # Coolify magic environment variable for port detection
      SERVICE_FQDN_ELIZA_3000: ""
      
      POSTGRES_URL: postgresql://eliza:eliza_secure_password@db:5432/eliza
      CHARACTER_FILE: /app/config/characters/server-bod.character.json
      STATIC_PATH: ./node_modules/@elizaos/cli/dist
      
      # AI Providers
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      
      # Integration Services
      DISCORD_APPLICATION_ID: ${DISCORD_APPLICATION_ID}
      DISCORD_API_TOKEN: ${DISCORD_API_TOKEN}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      
      # Security
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      
      # Performance
      MAX_MEMORY_USAGE: ${MAX_MEMORY_USAGE:-2048}
      RATE_LIMIT_REQUESTS: ${RATE_LIMIT_REQUESTS:-100}
    
    volumes:
      # Persistent data storage
      - eliza_data:/app/data
      - eliza_logs:/app/logs
    
    depends_on:
      db:
        condition: service_healthy
    
    # Coolify auto-detection magic
    labels:
      - "coolify.managed=true"
    
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    
    # Health check - check if the server is responding
    healthcheck:
      test: ["CMD", "bun", "/app/scripts/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # PostgreSQL Database
  db:
    image: ankane/pgvector:latest
    container_name: elizaos-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: eliza
      POSTGRES_USER: eliza
      POSTGRES_PASSWORD: eliza_secure_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Copy the init script instead of mounting as volume to avoid directory issues
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    
    # PostgreSQL port (for local development)
    ports:
      - "5432:5432"
    
    # Health check for database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eliza -d eliza"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.25'
volumes:
  eliza_data:
    driver: local
  eliza_logs:
    driver: local
  postgres_data:
    driver: local
  # redis_data:
  #   driver: local
 