version: '3.8'

services:
  # ElizaOS Production Service
  eliza:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elizaos-prod
    restart: unless-stopped
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"
      - "50000-50100:50000-50100/udp"
    environment:
      # Core Configuration
      NODE_ENV: ${NODE_ENV:-production}
      API_PORT: ${API_PORT:-3000}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      HOST: "0.0.0.0"
      
      POSTGRES_URL: postgresql://eliza:eliza_secure_password@db:5432/eliza
      
      # AI Providers
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      
      # Integration Services
      DISCORD_APPLICATION_ID: ${DISCORD_APPLICATION_ID}
      DISCORD_API_TOKEN: ${DISCORD_API_TOKEN}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      
      # Security
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      
      # Performance
      MAX_MEMORY_USAGE: ${MAX_MEMORY_USAGE:-2048}
      RATE_LIMIT_REQUESTS: ${RATE_LIMIT_REQUESTS:-100}
    
    volumes:
      # Persistent data storage
      - eliza_data:/app/data
      - eliza_logs:/app/logs
      # Character files (optional)
      - ./characters:/app/characters:ro
    
    depends_on:
      db:
        condition: service_healthy
    
    networks:
      - eliza-network
    
    # Coolify service identification labels
    labels:
      - "coolify.enabled=true"
      - "coolify.name=eliza"
      - "coolify.http.main=3000"
    
    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    
    # Health check - check if the server is responding
    healthcheck:
      test: ["CMD", "bun", "/app/healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # PostgreSQL Database
  db:
    image: ankane/pgvector:latest
    container_name: elizaos-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: eliza
      POSTGRES_USER: eliza
      POSTGRES_PASSWORD: eliza_secure_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Copy the init script instead of mounting as volume to avoid directory issues
      - ./init-db.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    
    networks:
      - eliza-network
    
    # Security: Don't expose PostgreSQL port externally in production
    # ports:
    #   - "5432:5432"
    
    # Health check for database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eliza -d eliza"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Redis Cache (Optional - for scaling)
  # redis:
  #   image: redis:7-alpine
  #   container_name: elizaos-redis
  #   restart: unless-stopped
  #   networks:
  #     - eliza-network
  #   volumes:
  #     - redis_data:/data
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

volumes:
  eliza_data:
    driver: local
  eliza_logs:
    driver: local
  postgres_data:
    driver: local
  # redis_data:
  #   driver: local

networks:
  eliza-network:
    driver: bridge
    name: elizaos-network 